language: php
services:
    - mysql

cache:
    yarn: true
    directories:
        - $HOME/.composer/cache/files

php:
    - '7.3'

env:
    global:
        - CC_TEST_REPORTER_ID="973ad6b3b21f6f9302f571fa3ca7b88a1b23f0d0a23894a49621fd5fe6d725a3"
    jobs:
        - APP_ENV=test DATABASE_URL="mysql://travis@localhost:3306/test_database"

before_install:
    - curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update
    - sudo apt-get install -y yarn
    - composer self-update
    - sh -c "yes '' | pecl install -f apcu"

install:
    - composer install
    - yarn install
    - php bin/console doctrine:database:create
    - php bin/console doctrine:migrations:migrate --allow-no-migration --no-interaction
    - yarn encore prod

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT; fi